sudo: required

language: go

services:
  - docker

go:
  - 1.10.3

before_install:
  - sudo apt-get install -y protoc
  - go get -vu github.com/golang/protobuf/protoc-gen-go
script:
  - make travis

