language: go

services:
  - docker

go:
  - "1.10"

before_install:
  - bash bin/install-protobuf.sh
  - go get -u github.com/golang/protobuf/protoc-gen-go
  - go get -u github.com/golang/protobuf/protoc-gen-micro
script:
  - make travis

