version: "3.4"

services:

  ### consul #############################################
  consul:
    image: consul
    ports:
      - 8500:8500

  ### RabbitMQ ###########################################
  rabbitmq:
    image: rabbitmq:3-management
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin
      - TZ=Europe/Berlin
    ports:
      - "5672:5672"
      - "6060:15672"

  ### api ##############################################
  api:
    image: microhq/micro
    command: api --handler=rpc --address=:8080 --namespace=go.micro.srv
    ports:
      - "8080:8080"
    environment:
      MICRO_REGISTRY: "consul"
      MICRO_REGISTRY_ADDRESS: "consul"

  ### mail #############################################
  mail:
    image: educonn/mail:latest
    environment:
      DEBUG: 1
      MICRO_REGISTRY: "consul"
      MICRO_REGISTRY_ADDRESS: "consul"
      SMTP_HOST: "smtp.mailtrap.io"
      SMTP_PORT: 2525
      SMTP_USERNAME: "0f92ba981e4a2f"
      SMTP_PASSWORD: "09f0dcb79f8f24"
    depends_on:
      - consul


  ### user ###########################################
  user:
    image: educonn/user:latest
    environment:
      MICRO_REGISTRY: "consul"
      MICRO_REGISTRY_ADDRESS: "consul"
      BROKER: "rabbitmq"
      BROKER_ADDRESS: "amqp://admin:admin@rabbitmq:5672"
      DEBUG: 1
      DB_HOST: "user-db"
      DB_NAME: "users"
      DB_USERNAME:  "users"
      DB_PASSWORD:  "secret"
      DB_PORT: "3306"
    depends_on:
      - consul
      - rabbitmq
      - user-db

  ### user-db ########################################
  user-db:
    image: mysql:5.7
    environment:
      MYSQL_USER: "users"
      MYSQL_PASSWORD: "secret"
      MYSQL_DATABASE: "users"
      MYSQL_ROOT_PASSWORD: "superSecret"
    ports:
      - 3306:3306
