// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/mail.proto

package go_micro_srv_email

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type EmailRequest struct {
	From                 string   `protobuf:"bytes,1,opt,name=from,proto3" json:"from,omitempty"`
	To                   string   `protobuf:"bytes,2,opt,name=to,proto3" json:"to,omitempty"`
	Subject              string   `protobuf:"bytes,3,opt,name=subject,proto3" json:"subject,omitempty"`
	Message              string   `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EmailRequest) Reset()         { *m = EmailRequest{} }
func (m *EmailRequest) String() string { return proto.CompactTextString(m) }
func (*EmailRequest) ProtoMessage()    {}
func (*EmailRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_mail_981ee799132b1a74, []int{0}
}
func (m *EmailRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EmailRequest.Unmarshal(m, b)
}
func (m *EmailRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EmailRequest.Marshal(b, m, deterministic)
}
func (dst *EmailRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EmailRequest.Merge(dst, src)
}
func (m *EmailRequest) XXX_Size() int {
	return xxx_messageInfo_EmailRequest.Size(m)
}
func (m *EmailRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_EmailRequest.DiscardUnknown(m)
}

var xxx_messageInfo_EmailRequest proto.InternalMessageInfo

func (m *EmailRequest) GetFrom() string {
	if m != nil {
		return m.From
	}
	return ""
}

func (m *EmailRequest) GetTo() string {
	if m != nil {
		return m.To
	}
	return ""
}

func (m *EmailRequest) GetSubject() string {
	if m != nil {
		return m.Subject
	}
	return ""
}

func (m *EmailRequest) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type Response struct {
	Code                 int32    `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_mail_981ee799132b1a74, []int{1}
}
func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (dst *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(dst, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *Response) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func init() {
	proto.RegisterType((*EmailRequest)(nil), "go.micro.srv.email.EmailRequest")
	proto.RegisterType((*Response)(nil), "go.micro.srv.email.Response")
}

func init() { proto.RegisterFile("proto/mail.proto", fileDescriptor_mail_981ee799132b1a74) }

var fileDescriptor_mail_981ee799132b1a74 = []byte{
	// 201 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x90, 0xbf, 0x4f, 0x87, 0x30,
	0x10, 0xc5, 0x43, 0xc5, 0x1f, 0x34, 0xc6, 0x98, 0x9b, 0x1a, 0xe3, 0x40, 0x98, 0x9c, 0x6a, 0xa2,
	0x8b, 0xff, 0x80, 0x93, 0x5b, 0x19, 0x9d, 0xa0, 0x1c, 0x04, 0x63, 0x39, 0x6c, 0x0b, 0x7f, 0xbf,
	0xe9, 0x09, 0x09, 0xe6, 0xfb, 0xdd, 0x3e, 0xf7, 0x5e, 0x2f, 0xf7, 0x5e, 0xe5, 0xfd, 0xec, 0x29,
	0xd2, 0xb3, 0x6b, 0xc6, 0x6f, 0xcd, 0x08, 0x30, 0x90, 0x76, 0xa3, 0xf5, 0xa4, 0x83, 0x5f, 0x35,
	0x26, 0xa7, 0xea, 0xe5, 0xed, 0x7b, 0x02, 0x83, 0x3f, 0x0b, 0x86, 0x08, 0x20, 0xf3, 0xde, 0x93,
	0x53, 0x59, 0x99, 0x3d, 0x15, 0x86, 0x19, 0xee, 0xa4, 0x88, 0xa4, 0x04, 0x2b, 0x22, 0x12, 0x28,
	0x79, 0x1d, 0x96, 0xf6, 0x0b, 0x6d, 0x54, 0x17, 0x2c, 0xee, 0x63, 0x72, 0x1c, 0x86, 0xd0, 0x0c,
	0xa8, 0xf2, 0x3f, 0x67, 0x1b, 0xab, 0x37, 0x79, 0x63, 0x30, 0xcc, 0x34, 0x05, 0x4c, 0x37, 0x2c,
	0x75, 0xc8, 0x37, 0x2e, 0x0d, 0xf3, 0x71, 0x53, 0xfc, 0xdb, 0x7c, 0xf9, 0xdc, 0x12, 0xd6, 0xe8,
	0xd7, 0xd1, 0x22, 0x7c, 0xc8, 0xa2, 0xc6, 0xa9, 0x63, 0x0d, 0x4a, 0x7d, 0xda, 0x49, 0x1f, 0x0b,
	0x3d, 0x3c, 0x9e, 0x7b, 0xb1, 0x47, 0x69, 0xaf, 0xf8, 0x67, 0x5e, 0x7f, 0x03, 0x00, 0x00, 0xff,
	0xff, 0x5f, 0xbe, 0x12, 0x50, 0x2d, 0x01, 0x00, 0x00,
}
