// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/course/course.proto

package educonn_course

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type CourseEntity struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title                string   `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description          string   `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Topics               []string `protobuf:"bytes,4,rep,name=topics,proto3" json:"topics,omitempty"`
	Type                 string   `protobuf:"bytes,5,opt,name=type,proto3" json:"type,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CourseEntity) Reset()         { *m = CourseEntity{} }
func (m *CourseEntity) String() string { return proto.CompactTextString(m) }
func (*CourseEntity) ProtoMessage()    {}
func (*CourseEntity) Descriptor() ([]byte, []int) {
	return fileDescriptor_course_7d10d6e961f07463, []int{0}
}
func (m *CourseEntity) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CourseEntity.Unmarshal(m, b)
}
func (m *CourseEntity) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CourseEntity.Marshal(b, m, deterministic)
}
func (dst *CourseEntity) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CourseEntity.Merge(dst, src)
}
func (m *CourseEntity) XXX_Size() int {
	return xxx_messageInfo_CourseEntity.Size(m)
}
func (m *CourseEntity) XXX_DiscardUnknown() {
	xxx_messageInfo_CourseEntity.DiscardUnknown(m)
}

var xxx_messageInfo_CourseEntity proto.InternalMessageInfo

func (m *CourseEntity) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *CourseEntity) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *CourseEntity) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *CourseEntity) GetTopics() []string {
	if m != nil {
		return m.Topics
	}
	return nil
}

func (m *CourseEntity) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

type Request struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}
func (*Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_course_7d10d6e961f07463, []int{1}
}
func (m *Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request.Unmarshal(m, b)
}
func (m *Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request.Marshal(b, m, deterministic)
}
func (dst *Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request.Merge(dst, src)
}
func (m *Request) XXX_Size() int {
	return xxx_messageInfo_Request.Size(m)
}
func (m *Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Request proto.InternalMessageInfo

type CourseResponse struct {
	Course               *CourseEntity   `protobuf:"bytes,1,opt,name=course,proto3" json:"course,omitempty"`
	Courses              []*CourseEntity `protobuf:"bytes,2,rep,name=courses,proto3" json:"courses,omitempty"`
	Errors               []*Error        `protobuf:"bytes,3,rep,name=errors,proto3" json:"errors,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *CourseResponse) Reset()         { *m = CourseResponse{} }
func (m *CourseResponse) String() string { return proto.CompactTextString(m) }
func (*CourseResponse) ProtoMessage()    {}
func (*CourseResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_course_7d10d6e961f07463, []int{2}
}
func (m *CourseResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CourseResponse.Unmarshal(m, b)
}
func (m *CourseResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CourseResponse.Marshal(b, m, deterministic)
}
func (dst *CourseResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CourseResponse.Merge(dst, src)
}
func (m *CourseResponse) XXX_Size() int {
	return xxx_messageInfo_CourseResponse.Size(m)
}
func (m *CourseResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CourseResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CourseResponse proto.InternalMessageInfo

func (m *CourseResponse) GetCourse() *CourseEntity {
	if m != nil {
		return m.Course
	}
	return nil
}

func (m *CourseResponse) GetCourses() []*CourseEntity {
	if m != nil {
		return m.Courses
	}
	return nil
}

func (m *CourseResponse) GetErrors() []*Error {
	if m != nil {
		return m.Errors
	}
	return nil
}

type Error struct {
	Code                 int32    `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Error) Reset()         { *m = Error{} }
func (m *Error) String() string { return proto.CompactTextString(m) }
func (*Error) ProtoMessage()    {}
func (*Error) Descriptor() ([]byte, []int) {
	return fileDescriptor_course_7d10d6e961f07463, []int{3}
}
func (m *Error) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Error.Unmarshal(m, b)
}
func (m *Error) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Error.Marshal(b, m, deterministic)
}
func (dst *Error) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Error.Merge(dst, src)
}
func (m *Error) XXX_Size() int {
	return xxx_messageInfo_Error.Size(m)
}
func (m *Error) XXX_DiscardUnknown() {
	xxx_messageInfo_Error.DiscardUnknown(m)
}

var xxx_messageInfo_Error proto.InternalMessageInfo

func (m *Error) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *Error) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func init() {
	proto.RegisterType((*CourseEntity)(nil), "educonn.course.CourseEntity")
	proto.RegisterType((*Request)(nil), "educonn.course.Request")
	proto.RegisterType((*CourseResponse)(nil), "educonn.course.CourseResponse")
	proto.RegisterType((*Error)(nil), "educonn.course.Error")
}

func init() { proto.RegisterFile("proto/course/course.proto", fileDescriptor_course_7d10d6e961f07463) }

var fileDescriptor_course_7d10d6e961f07463 = []byte{
	// 311 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x52, 0x4d, 0x4b, 0xc3, 0x40,
	0x10, 0x35, 0x49, 0xb3, 0xa5, 0x53, 0xe9, 0x61, 0xf0, 0x63, 0x15, 0x91, 0x90, 0x53, 0x2f, 0x46,
	0xa8, 0x1f, 0x77, 0x29, 0xa5, 0x9e, 0xf7, 0x1f, 0xd4, 0x64, 0x90, 0x85, 0x9a, 0x8d, 0xbb, 0x93,
	0x43, 0xaf, 0xfe, 0x1f, 0xff, 0x92, 0xbf, 0x45, 0xba, 0x9b, 0x40, 0x2d, 0x62, 0x0f, 0x9e, 0xf2,
	0xe6, 0xcd, 0x7b, 0x93, 0x37, 0x93, 0xc0, 0x45, 0x63, 0x0d, 0x9b, 0xdb, 0xd2, 0xb4, 0xd6, 0x51,
	0xf7, 0x28, 0x3c, 0x87, 0x13, 0xaa, 0xda, 0xd2, 0xd4, 0x75, 0x11, 0xd8, 0xfc, 0x23, 0x82, 0xe3,
	0xb9, 0x87, 0x8b, 0x9a, 0x35, 0x6f, 0x70, 0x02, 0xb1, 0xae, 0x64, 0x94, 0x45, 0xd3, 0x91, 0x8a,
	0x75, 0x85, 0x27, 0x90, 0xb2, 0xe6, 0x35, 0xc9, 0xd8, 0x53, 0xa1, 0xc0, 0x0c, 0xc6, 0x15, 0xb9,
	0xd2, 0xea, 0x86, 0xb5, 0xa9, 0x65, 0xe2, 0x7b, 0xbb, 0x14, 0x9e, 0x81, 0x60, 0xd3, 0xe8, 0xd2,
	0xc9, 0x41, 0x96, 0x4c, 0x47, 0xaa, 0xab, 0x10, 0x61, 0xc0, 0x9b, 0x86, 0x64, 0xea, 0x2d, 0x1e,
	0xe7, 0x23, 0x18, 0x2a, 0x7a, 0x6f, 0xc9, 0x71, 0xfe, 0x19, 0xc1, 0x24, 0xe4, 0x51, 0xe4, 0x1a,
	0x53, 0x3b, 0xc2, 0x7b, 0x10, 0x21, 0xac, 0x4f, 0x35, 0x9e, 0x5d, 0x15, 0x3f, 0x77, 0x28, 0x76,
	0xf3, 0xab, 0x4e, 0x8b, 0x8f, 0x30, 0x0c, 0xc8, 0xc9, 0x38, 0x4b, 0x0e, 0xda, 0x7a, 0x31, 0xde,
	0x80, 0x20, 0x6b, 0x8d, 0x75, 0x32, 0xf1, 0xb6, 0xd3, 0x7d, 0xdb, 0x62, 0xdb, 0x55, 0x9d, 0x28,
	0x7f, 0x80, 0xd4, 0x13, 0xdb, 0xbd, 0x4a, 0x53, 0x85, 0x8c, 0xa9, 0xf2, 0x18, 0x25, 0x0c, 0xdf,
	0xc8, 0xb9, 0xd5, 0x6b, 0x7f, 0xbd, 0xbe, 0x9c, 0x7d, 0x45, 0x20, 0xc2, 0xfb, 0xf1, 0x19, 0xc4,
	0xdc, 0xd2, 0x8a, 0x09, 0xff, 0x4c, 0x78, 0x79, 0xfd, 0x7b, 0xb7, 0x3f, 0x53, 0x7e, 0x84, 0x0b,
	0x48, 0x96, 0xc4, 0xff, 0x1e, 0x33, 0x07, 0xb1, 0x24, 0x7e, 0x5a, 0xaf, 0xf1, 0x7c, 0x5f, 0xdb,
	0x7d, 0xa5, 0xc3, 0x43, 0x5e, 0x84, 0xff, 0xdd, 0xee, 0xbe, 0x03, 0x00, 0x00, 0xff, 0xff, 0x08,
	0x1d, 0xe9, 0xf8, 0x8b, 0x02, 0x00, 0x00,
}
