// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/user/events.proto

package go_micro_srv_user

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type UserCreatedEvent struct {
	Id                   string   `protobuf:"bytes,1,opt,name=Id,proto3" json:"Id,omitempty"`
	Email                string   `protobuf:"bytes,2,opt,name=Email,proto3" json:"Email,omitempty"`
	FirstName            string   `protobuf:"bytes,3,opt,name=FirstName,proto3" json:"FirstName,omitempty"`
	LastName             string   `protobuf:"bytes,4,opt,name=LastName,proto3" json:"LastName,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserCreatedEvent) Reset()         { *m = UserCreatedEvent{} }
func (m *UserCreatedEvent) String() string { return proto.CompactTextString(m) }
func (*UserCreatedEvent) ProtoMessage()    {}
func (*UserCreatedEvent) Descriptor() ([]byte, []int) {
	return fileDescriptor_events_8a87aec0a8761a9b, []int{0}
}
func (m *UserCreatedEvent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserCreatedEvent.Unmarshal(m, b)
}
func (m *UserCreatedEvent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserCreatedEvent.Marshal(b, m, deterministic)
}
func (dst *UserCreatedEvent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserCreatedEvent.Merge(dst, src)
}
func (m *UserCreatedEvent) XXX_Size() int {
	return xxx_messageInfo_UserCreatedEvent.Size(m)
}
func (m *UserCreatedEvent) XXX_DiscardUnknown() {
	xxx_messageInfo_UserCreatedEvent.DiscardUnknown(m)
}

var xxx_messageInfo_UserCreatedEvent proto.InternalMessageInfo

func (m *UserCreatedEvent) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *UserCreatedEvent) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *UserCreatedEvent) GetFirstName() string {
	if m != nil {
		return m.FirstName
	}
	return ""
}

func (m *UserCreatedEvent) GetLastName() string {
	if m != nil {
		return m.LastName
	}
	return ""
}

func init() {
	proto.RegisterType((*UserCreatedEvent)(nil), "go.micro.srv.user.UserCreatedEvent")
}

func init() { proto.RegisterFile("proto/user/events.proto", fileDescriptor_events_8a87aec0a8761a9b) }

var fileDescriptor_events_8a87aec0a8761a9b = []byte{
	// 148 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x2f, 0x28, 0xca, 0x2f,
	0xc9, 0xd7, 0x2f, 0x2d, 0x4e, 0x2d, 0xd2, 0x4f, 0x2d, 0x4b, 0xcd, 0x2b, 0x29, 0xd6, 0x03, 0x8b,
	0x08, 0x09, 0xa6, 0xe7, 0xeb, 0xe5, 0x66, 0x26, 0x17, 0xe5, 0xeb, 0x15, 0x17, 0x95, 0xe9, 0x81,
	0xe4, 0x95, 0x8a, 0xb8, 0x04, 0x42, 0x8b, 0x53, 0x8b, 0x9c, 0x8b, 0x52, 0x13, 0x4b, 0x52, 0x53,
	0x5c, 0x41, 0xaa, 0x85, 0xf8, 0xb8, 0x98, 0x3c, 0x53, 0x24, 0x18, 0x15, 0x18, 0x35, 0x38, 0x83,
	0x98, 0x3c, 0x53, 0x84, 0x44, 0xb8, 0x58, 0x5d, 0x73, 0x13, 0x33, 0x73, 0x24, 0x98, 0xc0, 0x42,
	0x10, 0x8e, 0x90, 0x0c, 0x17, 0xa7, 0x5b, 0x66, 0x51, 0x71, 0x89, 0x5f, 0x62, 0x6e, 0xaa, 0x04,
	0x33, 0x58, 0x06, 0x21, 0x20, 0x24, 0xc5, 0xc5, 0xe1, 0x93, 0x08, 0x95, 0x64, 0x01, 0x4b, 0xc2,
	0xf9, 0x49, 0x6c, 0x60, 0xd7, 0x18, 0x03, 0x02, 0x00, 0x00, 0xff, 0xff, 0x2a, 0x2f, 0x96, 0x3d,
	0xa8, 0x00, 0x00, 0x00,
}
