// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/user/user.proto

package go_micro_srv_user

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type User struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	FirstName            string   `protobuf:"bytes,2,opt,name=firstName,proto3" json:"firstName,omitempty"`
	LastName             string   `protobuf:"bytes,3,opt,name=lastName,proto3" json:"lastName,omitempty"`
	Email                string   `protobuf:"bytes,4,opt,name=email,proto3" json:"email,omitempty"`
	Password             string   `protobuf:"bytes,5,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_user_b2108a50941cfda4, []int{0}
}
func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (dst *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(dst, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *User) GetFirstName() string {
	if m != nil {
		return m.FirstName
	}
	return ""
}

func (m *User) GetLastName() string {
	if m != nil {
		return m.LastName
	}
	return ""
}

func (m *User) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *User) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type Request struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}
func (*Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_user_b2108a50941cfda4, []int{1}
}
func (m *Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request.Unmarshal(m, b)
}
func (m *Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request.Marshal(b, m, deterministic)
}
func (dst *Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request.Merge(dst, src)
}
func (m *Request) XXX_Size() int {
	return xxx_messageInfo_Request.Size(m)
}
func (m *Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Request proto.InternalMessageInfo

type UserResponse struct {
	User                 *User    `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	Users                []*User  `protobuf:"bytes,2,rep,name=users,proto3" json:"users,omitempty"`
	Errors               []*Error `protobuf:"bytes,3,rep,name=errors,proto3" json:"errors,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserResponse) Reset()         { *m = UserResponse{} }
func (m *UserResponse) String() string { return proto.CompactTextString(m) }
func (*UserResponse) ProtoMessage()    {}
func (*UserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_user_b2108a50941cfda4, []int{2}
}
func (m *UserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserResponse.Unmarshal(m, b)
}
func (m *UserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserResponse.Marshal(b, m, deterministic)
}
func (dst *UserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserResponse.Merge(dst, src)
}
func (m *UserResponse) XXX_Size() int {
	return xxx_messageInfo_UserResponse.Size(m)
}
func (m *UserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UserResponse proto.InternalMessageInfo

func (m *UserResponse) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

func (m *UserResponse) GetUsers() []*User {
	if m != nil {
		return m.Users
	}
	return nil
}

func (m *UserResponse) GetErrors() []*Error {
	if m != nil {
		return m.Errors
	}
	return nil
}

type Token struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	Valid                bool     `protobuf:"varint,2,opt,name=valid,proto3" json:"valid,omitempty"`
	Errors               []*Error `protobuf:"bytes,3,rep,name=errors,proto3" json:"errors,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Token) Reset()         { *m = Token{} }
func (m *Token) String() string { return proto.CompactTextString(m) }
func (*Token) ProtoMessage()    {}
func (*Token) Descriptor() ([]byte, []int) {
	return fileDescriptor_user_b2108a50941cfda4, []int{3}
}
func (m *Token) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Token.Unmarshal(m, b)
}
func (m *Token) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Token.Marshal(b, m, deterministic)
}
func (dst *Token) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Token.Merge(dst, src)
}
func (m *Token) XXX_Size() int {
	return xxx_messageInfo_Token.Size(m)
}
func (m *Token) XXX_DiscardUnknown() {
	xxx_messageInfo_Token.DiscardUnknown(m)
}

var xxx_messageInfo_Token proto.InternalMessageInfo

func (m *Token) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *Token) GetValid() bool {
	if m != nil {
		return m.Valid
	}
	return false
}

func (m *Token) GetErrors() []*Error {
	if m != nil {
		return m.Errors
	}
	return nil
}

type Error struct {
	Code                 int32    `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Description          string   `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Error) Reset()         { *m = Error{} }
func (m *Error) String() string { return proto.CompactTextString(m) }
func (*Error) ProtoMessage()    {}
func (*Error) Descriptor() ([]byte, []int) {
	return fileDescriptor_user_b2108a50941cfda4, []int{4}
}
func (m *Error) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Error.Unmarshal(m, b)
}
func (m *Error) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Error.Marshal(b, m, deterministic)
}
func (dst *Error) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Error.Merge(dst, src)
}
func (m *Error) XXX_Size() int {
	return xxx_messageInfo_Error.Size(m)
}
func (m *Error) XXX_DiscardUnknown() {
	xxx_messageInfo_Error.DiscardUnknown(m)
}

var xxx_messageInfo_Error proto.InternalMessageInfo

func (m *Error) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *Error) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func init() {
	proto.RegisterType((*User)(nil), "go.micro.srv.user.User")
	proto.RegisterType((*Request)(nil), "go.micro.srv.user.Request")
	proto.RegisterType((*UserResponse)(nil), "go.micro.srv.user.UserResponse")
	proto.RegisterType((*Token)(nil), "go.micro.srv.user.Token")
	proto.RegisterType((*Error)(nil), "go.micro.srv.user.Error")
}

func init() { proto.RegisterFile("proto/user/user.proto", fileDescriptor_user_b2108a50941cfda4) }

var fileDescriptor_user_b2108a50941cfda4 = []byte{
	// 369 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x93, 0x4d, 0x4b, 0xf3, 0x40,
	0x10, 0xc7, 0x9b, 0xd7, 0xa7, 0x9d, 0x3e, 0x0a, 0x0e, 0x8a, 0xa1, 0x08, 0x96, 0x9c, 0x04, 0x31,
	0x4a, 0x3d, 0x8a, 0x87, 0xa2, 0xa5, 0x37, 0x0f, 0x41, 0xbd, 0xc7, 0x66, 0xd4, 0xc5, 0xb4, 0x1b,
	0x77, 0xb7, 0xf5, 0xee, 0xe7, 0xf0, 0xa3, 0xf9, 0x61, 0x64, 0x27, 0xf1, 0x05, 0x6c, 0x8a, 0xe8,
	0xa5, 0xdd, 0xff, 0xcc, 0x6f, 0x67, 0x67, 0xe6, 0x4f, 0x60, 0xab, 0x54, 0xd2, 0xc8, 0xc3, 0xb9,
	0x26, 0xc5, 0x3f, 0x09, 0x6b, 0xdc, 0xb8, 0x93, 0xc9, 0x54, 0x4c, 0x94, 0x4c, 0xb4, 0x5a, 0x24,
	0x36, 0x11, 0x3f, 0x3b, 0xe0, 0x5f, 0x69, 0x52, 0xb8, 0x0e, 0xae, 0xc8, 0x23, 0xa7, 0xef, 0xec,
	0x75, 0x52, 0x57, 0xe4, 0xb8, 0x03, 0x9d, 0x5b, 0xa1, 0xb4, 0xb9, 0xc8, 0xa6, 0x14, 0xb9, 0x1c,
	0xfe, 0x0c, 0x60, 0x0f, 0xda, 0x45, 0x56, 0x27, 0x3d, 0x4e, 0x7e, 0x68, 0xdc, 0x84, 0x80, 0xa6,
	0x99, 0x28, 0x22, 0x9f, 0x13, 0x95, 0xb0, 0x37, 0xca, 0x4c, 0xeb, 0x27, 0xa9, 0xf2, 0x28, 0xa8,
	0x6e, 0xbc, 0xeb, 0xb8, 0x03, 0xff, 0x52, 0x7a, 0x9c, 0x93, 0x36, 0xf1, 0x8b, 0x03, 0xff, 0x6d,
	0x3f, 0x29, 0xe9, 0x52, 0xce, 0x34, 0xe1, 0x3e, 0xf8, 0xb6, 0x51, 0xee, 0xac, 0x3b, 0xd8, 0x4e,
	0xbe, 0x8d, 0x90, 0x30, 0xce, 0x10, 0x1e, 0x40, 0x60, 0xff, 0x75, 0xe4, 0xf6, 0xbd, 0x55, 0x74,
	0x45, 0xe1, 0x11, 0x84, 0xa4, 0x94, 0x54, 0x3a, 0xf2, 0x98, 0x8f, 0x96, 0xf0, 0x23, 0x0b, 0xa4,
	0x35, 0x17, 0x13, 0x04, 0x97, 0xf2, 0x81, 0x66, 0x76, 0x48, 0x63, 0x0f, 0xf5, 0xc6, 0x2a, 0x61,
	0xa3, 0x8b, 0xac, 0x10, 0x39, 0x2f, 0xac, 0x9d, 0x56, 0xe2, 0x17, 0xcf, 0x9c, 0x42, 0xc0, 0x01,
	0x44, 0xf0, 0x27, 0x32, 0x27, 0x7e, 0x25, 0x48, 0xf9, 0x8c, 0x7d, 0xe8, 0xe6, 0xa4, 0x27, 0x4a,
	0x94, 0x46, 0xc8, 0x59, 0xed, 0xcd, 0xd7, 0xd0, 0xe0, 0xd5, 0x05, 0x7f, 0x38, 0x37, 0xf7, 0x78,
	0x0e, 0xe1, 0x99, 0xa2, 0xcc, 0x10, 0x36, 0xad, 0xa2, 0xb7, 0xdb, 0xb4, 0xa3, 0xda, 0x80, 0xb8,
	0x85, 0x43, 0xf0, 0xc6, 0x64, 0xfe, 0x54, 0x62, 0x0c, 0xe1, 0x98, 0xcc, 0xb0, 0x28, 0xb0, 0xb7,
	0x04, 0xae, 0xcd, 0xff, 0x49, 0xa1, 0x93, 0x7a, 0xb2, 0xc6, 0x66, 0x96, 0x2d, 0x97, 0x2d, 0x8b,
	0x5b, 0x38, 0x82, 0xb5, 0x6b, 0xeb, 0x48, 0x66, 0xa8, 0x72, 0xb1, 0x11, 0x5e, 0x55, 0xe6, 0x26,
	0xe4, 0xaf, 0xe9, 0xf8, 0x2d, 0x00, 0x00, 0xff, 0xff, 0x9c, 0x4e, 0x53, 0x84, 0x66, 0x03, 0x00,
	0x00,
}
